language: "python"
matrix:
  include:
    - python: "3.9"
    - python: "3.8"
    - python: "3.7"
    - python: "3.6"
install:
  - pip install .
  - pip install -r requirements_dev.txt
  - pip install codecov
script:
  - python setup.py build
  - pytest --cov=nanolib --cov-report term --cov-report xml tests
  - python setup.py speed
after_success:
  - codecov
