language: "python"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.6"
    - arch: arm64
      python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install .
  - pip install -r requirements_dev.txt
  - pip install codecov
script:
  - python setup.py build
  - pytest --cov=nanolib --cov-report term --cov-report xml tests
  - python setup.py speed
after_success:
  - codecov
